---
title: Додай шрифти з Google
hero_image: images/banner.png
description: Додай шрифти з Google.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Додай шрифти з Google
