title: Ajouter des polices Google
hero_image: images/banner.png
description: Ajoute des polices Google.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Ajouter des polices Google
